<?php

namespace Database\Seeders;

use App\Enums\Ticketing\TicketOrderStatus;
use App\Models\Attendee;
use App\Models\Event;
use App\Models\ScanLog;
use App\Models\Ticket;
use App\Models\TicketOrder;
use App\Models\TicketOrderItem;
use App\Models\User;
use App\Services\Ticket\TicketPurchaseService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Seeds realistic, named sample attendees for the Global AI Expo 2026 event so
 * the scanner, attendee management and check-in screens have data to work with.
 *
 * One confirmed + paid order per ticket type holds its attendees; each paid
 * order carries a payment channel + the project's active gateway so the admin
 * table shows Payment / Mode columns (instead of "-"). ~1 in 7 attendees is
 * pre-checked-in to exercise the check-in UI. Names/emails are explicit so the
 * placeholder ("Tamu #n") path is bypassed. qr_token + ulid are generated by
 * Attendee::boot, so every attendee is scannable.
 *
 * Resettable: every run first hard-deletes its own sentinel batch (orders,
 * items, attendees, scan logs) and recreates it fresh - never touches real
 * public orders. Safe to run on production:
 * php artisan db:seed --class=GlobalAiExpoAttendeesSeeder
 */
class GlobalAiExpoAttendeesSeeder extends Seeder
{
    private const PROJECT_USERNAME = 'globalaiexpo';

    private const BATCH_LABEL = 'Seeder: Global AI Expo Attendees';

    /**
     * Payment channels cycled across paid orders so the Payment column reads
     * like real Xendit virtual-account / QRIS settlements.
     *
     * @var list<string>
     */
    private const CHANNELS = ['BCA', 'QRIS', 'MANDIRI', 'BNI', 'PERMATA'];

    /**
     * Ticket slug => attendee full names. Distribution: 18/8/6/6/4 = 42 total.
     *
     * @var array<string, list<string>>
     */
    private const ATTENDEES = [
        'regular-ticket' => [
            'Budi Santoso', 'Siti Nurhaliza', 'Andi Wijaya', 'Dewi Lestari',
            'Rizki Pratama', 'Putri Maharani', 'Eko Saputra', 'Rina Kartika',
            'Agus Setiawan', 'Maya Anggraini', 'Fajar Nugroho', 'Indah Permata',
            'Hendra Gunawan', 'Lia Marlina', 'Doni Kurniawan', 'Sri Wahyuni',
            'Bayu Aji', 'Nadia Safitri',
        ],
        'vip-ticket' => [
            'Reza Pahlevi', 'Anita Salim', 'Bambang Sutrisno', 'Clara Wijoyo',
            'Gilang Ramadhan', 'Vania Kusuma', 'Yusuf Hidayat', 'Tania Pertiwi',
        ],
        '3-day-bundle' => [
            'Arif Rahman', 'Mega Puspita', 'Dimas Prayoga', 'Ayu Larasati',
            'Teguh Iskandar', 'Fitri Handayani',
        ],
        'conference-pass' => [
            'Rangga Mahendra', 'Sasha Dewanti', 'Iwan Setiabudi', 'Linda Octaviani',
            'Yoga Pranata', 'Cinta Amelia',
        ],
        'meet-and-greet' => [
            'Galih Saputro', 'Bella Anjani', 'Faisal Akbar', 'Karina Putri',
        ],
    ];

    public function run(): void
    {
        $event = Event::query()
            ->whereHas('project', fn ($q) => $q->where('username', self::PROJECT_USERNAME))
            ->where('is_active', true)
            ->latest()
            ->first();

        if (! $event) {
            $this->command?->warn('Global AI Expo event not found; nothing to seed.');

            return;
        }

        $this->purgeBatch($event);

        $purchases = app(TicketPurchaseService::class);
        $gateway = $event->project?->activePaymentGateway();
        $staffId = $this->resolveStaffId();
        $created = 0;
        $checkedIn = 0;
        $globalIndex = 0;
        $orderIndex = 0;

        DB::transaction(function () use ($event, $purchases, $gateway, $staffId, &$created, &$checkedIn, &$globalIndex, &$orderIndex) {
            foreach (self::ATTENDEES as $slug => $names) {
                $ticket = Ticket::query()
                    ->where('event_id', $event->id)
                    ->where('slug', $slug)
                    ->first();

                if (! $ticket) {
                    $this->command?->warn("Ticket '{$slug}' not found; skipping.");

                    continue;
                }

                $ticket->loadMissing('pricePhases');
                $phase = $purchases->resolveActivePhase($ticket);
                $unitPrice = $phase ? (float) $phase->price : 0.0;
                $quantity = count($names);
                $total = $unitPrice * $quantity;
                $isFree = $total <= 0.0;

                $order = TicketOrder::query()->create([
                    'event_id' => $event->id,
                    'status' => TicketOrderStatus::Confirmed,
                    'buyer_name' => $names[0],
                    'buyer_email' => $this->emailFor($names[0]),
                    'buyer_phone' => '0811'.str_pad((string) random_int(0, 9999999), 7, '0', STR_PAD_LEFT),
                    'subtotal' => $total,
                    'discount_amount' => 0,
                    'total' => $total,
                    'payment_channel' => $isFree ? null : self::CHANNELS[$orderIndex % count(self::CHANNELS)],
                    'payment_gateway_id' => $isFree ? null : $gateway?->id,
                    'payment_ref' => $isFree ? null : 'SEED-'.Str::upper(Str::random(10)),
                    'paid_at' => now(),
                    'source' => 'seeder',
                    'batch_label' => self::BATCH_LABEL,
                ]);
                $orderIndex++;

                $item = $order->items()->create([
                    'ticket_id' => $ticket->id,
                    'quantity' => $quantity,
                    'unit_price' => $unitPrice,
                    'phase_label' => $phase?->label,
                    'subtotal' => $total,
                ]);

                foreach ($names as $name) {
                    $globalIndex++;
                    $isCheckedIn = $globalIndex % 7 === 0;

                    $item->attendees()->create([
                        'ticket_id' => $ticket->id,
                        'name' => $name,
                        'email' => $this->emailFor($name),
                        'personalized_at' => now(),
                        'checked_in_at' => $isCheckedIn ? now() : null,
                        'checked_in_by' => $isCheckedIn ? $staffId : null,
                        'checkin_event_id' => $isCheckedIn ? $event->id : null,
                    ]);

                    $created++;
                    $checkedIn += $isCheckedIn ? 1 : 0;
                }
            }
        });

        $this->command?->info("Seeded {$created} attendees for Global AI Expo 2026 ({$checkedIn} checked-in).");
    }

    /**
     * Hard-delete this seeder's previous sentinel batch (orders, items,
     * attendees, scan logs) so a re-run produces fresh, scannable data. Scoped
     * strictly to the sentinel batch_label - real public orders are untouched.
     */
    private function purgeBatch(Event $event): void
    {
        $orderIds = TicketOrder::withTrashed()
            ->where('event_id', $event->id)
            ->where('batch_label', self::BATCH_LABEL)
            ->pluck('id');

        if ($orderIds->isEmpty()) {
            return;
        }

        $itemIds = TicketOrderItem::withTrashed()
            ->whereIn('ticket_order_id', $orderIds)
            ->pluck('id');

        $attendeeIds = Attendee::withTrashed()
            ->whereIn('ticket_order_item_id', $itemIds)
            ->pluck('id');

        DB::transaction(function () use ($orderIds, $itemIds, $attendeeIds) {
            ScanLog::query()->whereIn('attendee_id', $attendeeIds)->delete();
            Attendee::withTrashed()->whereIn('id', $attendeeIds)->forceDelete();
            TicketOrderItem::withTrashed()->whereIn('id', $itemIds)->forceDelete();
            TicketOrder::withTrashed()->whereIn('id', $orderIds)->forceDelete();
        });

        $this->command?->info("Purged {$orderIds->count()} previously seeded order(s).");
    }

    /**
     * A staff/admin user id to stamp on pre-checked-in attendees, or null.
     */
    private function resolveStaffId(): ?int
    {
        $staff = User::query()
            ->whereHas('roles', fn ($q) => $q->whereIn('name', ['master', 'admin', 'staff']))
            ->value('id');

        return $staff ?? User::query()->value('id');
    }

    private function emailFor(string $name): string
    {
        $handle = Str::of($name)->lower()->ascii()->replaceMatches('/[^a-z]+/', '.')->trim('.');

        return "{$handle}@example.com";
    }
}
