import { defineComponentDoc } from "./define";

export default defineComponentDoc({
  name: "chart-bar",
  title: "Bar Chart",
  description:
    "Bar charts built on unovis-vue. One ChartBar covers vertical/horizontal orientation, single or grouped series, and stacking.",
  installation: {
    importPath: "@/components/ui/chart",
    imports: ["ChartBar", "ChartBarInteractive"],
  },
  sections: [
    {
      id: "default",
      title: "Default",
      description: "A single-series vertical bar chart.",
      examples: ["default"],
      align: "start",
    },
    {
      id: "horizontal",
      title: "Horizontal",
      description: "Flip the orientation with the horizontal prop.",
      examples: ["horizontal"],
      align: "start",
    },
    {
      id: "multiple",
      title: "Multiple",
      description: "Grouped bars for multiple series.",
      examples: ["multiple"],
      align: "start",
    },
    {
      id: "stacked",
      title: "Stacked",
      description: "Stack multiple series with the stacked prop.",
      examples: ["stacked"],
      align: "start",
    },
    {
      id: "interactive",
      title: "Interactive",
      description: "Toggle between series; totals update in the header.",
      examples: ["interactive"],
      align: "start",
    },
    {
      id: "basic",
      title: "Basic (card)",
      description: "A single-series bar in a card with a header, trend badge, and grid.",
      examples: ["basic"],
      align: "start",
    },
    {
      id: "market-share",
      title: "Multi-dataset (card)",
      description: "Grouped series in a card with a trend badge.",
      examples: ["market-share"],
      align: "start",
    },
    {
      id: "pattern-stripe",
      title: "Diagonal stripe pattern",
      description: "Frame a bar with a diagonal stripe SVG pattern via svgDefs + barFill.",
      examples: ["pattern-stripe"],
      align: "start",
    },
    {
      id: "pattern-stripe-multi",
      title: "Striped and solid",
      description: "Mix a stripe-filled series with a solid one using a per-key barFill map.",
      examples: ["pattern-stripe-multi"],
      align: "start",
    },
    {
      id: "pattern-dotted",
      title: "Dotted pattern",
      description: "An elegant dotted SVG pattern fill with a matching stroke.",
      examples: ["pattern-dotted"],
      align: "start",
    },
    {
      id: "pattern-dotted-multi",
      title: "Dotted and solid",
      description: "Compare a dotted series against a solid one.",
      examples: ["pattern-dotted-multi"],
      align: "start",
    },
    {
      id: "gradient-shape",
      title: "Gradient",
      description: "A soft vertical gradient fill via a linearGradient def.",
      examples: ["gradient-shape"],
      align: "start",
    },
    {
      id: "duotone",
      title: "Duotone gradient",
      description: "A 50/50 duotone fill using a hard-stop horizontal gradient.",
      examples: ["duotone"],
      align: "start",
    },
    {
      id: "gradient-3d",
      title: "3D gradient",
      description: "An isometric 3D bar with gradient faces, rendered by ChartBar3D.",
      examples: ["gradient-3d"],
      align: "start",
    },
    {
      id: "isometric-3d",
      title: "3D isometric",
      description: "A solid isometric 3D bar with shaded faces.",
      examples: ["isometric-3d"],
      align: "start",
    },
    {
      id: "animated",
      title: "Animated",
      description: "Bars collapse to a tick and expand on hover, surfacing the value.",
      examples: ["animated"],
      align: "start",
    },
    {
      id: "vertical",
      title: "Vertical (horizontal layout)",
      description: "A horizontal, grouped bar chart with category labels on the left.",
      examples: ["vertical"],
      align: "start",
    },
  ],
  apiReference: [
    {
      component: "ChartBar",
      props: [
        { name: "data", type: "Record<string, any>[]", default: "—", description: "Series rows." },
        { name: "config", type: "ChartConfig", default: "—", description: "Map of key → { label, color }." },
        { name: "dataKey", type: "string", default: "\"value\"", description: "Single-series row key." },
        { name: "dataKeys", type: "string[]", default: "null", description: "Multi-series row keys (overrides dataKey)." },
        { name: "xKey", type: "string", default: "\"date\"", description: "Row key for the category axis." },
        { name: "horizontal", type: "boolean", default: "false", description: "Render horizontal bars." },
        { name: "stacked", type: "boolean", default: "false", description: "Stack multi-series bars." },
        { name: "legend", type: "boolean", default: "false", description: "Render a legend below the chart." },
        { name: "roundedCorners", type: "number", default: "6", description: "Bar corner radius." },
        { name: "barPadding", type: "number", default: "0.2", description: "Fraction of each band left empty between bars." },
        { name: "grid", type: "boolean", default: "false", description: "Draw horizontal grid lines behind the bars." },
        { name: "svgDefs", type: "string", default: "null", description: "Raw SVG <defs> string (patterns/gradients/filters) injected into the chart." },
        { name: "barFill", type: "string | Record<string, string>", default: "null", description: "Override the fill; a string for every series or a per-key map (e.g. url(#pattern))." },
        { name: "barStroke", type: "string", default: "null", description: "Outline color drawn around every bar." },
        { name: "barStrokeWidth", type: "number", default: "1", description: "Outline width." },
        { name: "xTickFormatter", type: "(d) => string", default: "null", description: "Custom category tick formatter." },
        { name: "yTickFormatter", type: "(d) => string", default: "null", description: "Custom value tick formatter." },
      ],
    },
    {
      component: "ChartBar3D",
      props: [
        { name: "data", type: "Record<string, any>[]", default: "—", description: "Series rows." },
        { name: "config", type: "ChartConfig", default: "—", description: "Map of key → { label, color }." },
        { name: "xKey", type: "string", default: "\"month\"", description: "Row key for the category axis." },
        { name: "valueKey", type: "string", default: "\"value\"", description: "Row key for the bar value." },
        { name: "mode", type: "\"gradient\" | \"solid\"", default: "\"gradient\"", description: "Gradient faces or a single color with shaded faces." },
        { name: "colorOverride", type: "string", default: "null", description: "Override the bar color." },
        { name: "barCategoryGap", type: "number", default: "0.2", description: "Fraction of each band left as gap." },
      ],
    },
    {
      component: "ChartBarAnimated",
      props: [
        { name: "data", type: "Record<string, any>[]", default: "—", description: "Series rows." },
        { name: "config", type: "ChartConfig", default: "—", description: "Map of key → { label, color }." },
        { name: "xKey", type: "string", default: "\"month\"", description: "Row key for the category axis." },
        { name: "valueKey", type: "string", default: "\"value\"", description: "Row key for the bar value." },
        { name: "colorOverride", type: "string", default: "null", description: "Override the bar color." },
      ],
      events: [
        { name: "update:active", description: "Fires with the hovered bar's value (or null on leave)." },
      ],
    },
    {
      component: "ChartBarInteractive",
      props: [
        { name: "data", type: "Record<string, any>[]", default: "—", description: "Series rows." },
        { name: "config", type: "ChartConfig", default: "—", description: "Theming map; series with a color become toggles." },
        { name: "dataKeys", type: "string[]", default: "null", description: "Override which series are selectable." },
        { name: "xKey", type: "string", default: "\"date\"", description: "Row key for the category axis." },
        { name: "title", type: "string", default: "\"\"", description: "Optional header title." },
        { name: "description", type: "string", default: "\"\"", description: "Optional header description." },
      ],
    },
  ],
});
