import { defineComponentDoc } from "./define";

export default defineComponentDoc({
  name: "slider",
  title: "Slider",
  description: "Continuous or stepped range input for numeric values. Supports single or multi-thumb selection.",
  installation: { importPath: "@/components/ui/slider", imports: ["Slider"] },
  sections: [
    { id: "default", title: "Default", description: "Single thumb, 0-100.", examples: ["default"] },
    { id: "range", title: "Range", description: "Two thumbs for selecting a range.", examples: ["range"] },
    { id: "stepped", title: "Stepped", description: "Snap to discrete step values.", examples: ["stepped"] },
    { id: "wide-thumb", title: "Wide thumb", description: "Pill-shaped handle wider than it is tall, suited to open/close style controls.", examples: ["wide-thumb"] },
    { id: "ruler", title: "Ruler scrubber", description: "Recessed tick-ruler with a thin glowing indicator and a paired number input, matching design-tool property panels.", examples: ["ruler"] },
    { id: "simple", title: "Simple", description: "Basic slider with a label.", examples: ["simple"] },
    { id: "disabled", title: "Disabled", description: "Non-interactive, dimmed state.", examples: ["disabled"] },
    { id: "square-thumb", title: "Square thumb", description: "Thumb with squared-off corners.", examples: ["square-thumb"] },
    { id: "solid-thumb", title: "Solid thumb", description: "Filled thumb over a faded track.", examples: ["solid-thumb"] },
    { id: "tiny-thumb", title: "Tiny thumb", description: "Slim bar-style thumb.", examples: ["tiny-thumb"] },
    { id: "reference-labels", title: "Reference labels", description: "Static reference labels beneath the track.", examples: ["reference-labels"] },
    { id: "ticks", title: "Ticks", description: "Tick marks with skipped value labels.", examples: ["ticks"] },
    { id: "output", title: "With output", description: "Live value shown beside the label.", examples: ["output"] },
    { id: "labels", title: "With labels", description: "Descriptive labels above the track.", examples: ["labels"] },
    { id: "labels-tooltip", title: "Labels and tooltip", description: "Labels plus a value tooltip on the thumb.", examples: ["labels-tooltip"] },
    { id: "dual-range", title: "Dual range", description: "Two thumbs selecting a min and max.", examples: ["dual-range"] },
    { id: "dual-range-output", title: "Dual range with output", description: "Range with a live min-max output.", examples: ["dual-range-output"] },
    { id: "volume", title: "Volume", description: "Volume control flanked by icons.", examples: ["volume"] },
    { id: "multiple-thumbs", title: "Multiple thumbs", description: "Three thumbs with formatted tooltips.", examples: ["multiple-thumbs"] },
    { id: "temperature-input", title: "Temperature", description: "Slider synced with an input and a reset action.", examples: ["temperature-input"] },
    { id: "with-input", title: "With input", description: "Slider synced with a number input.", examples: ["with-input"] },
    { id: "rating-emoji", title: "Rating with emoji", description: "1-5 rating flanked by emoji.", examples: ["rating-emoji"] },
    { id: "rating-tooltip", title: "Rating with tooltip", description: "Rating with a label tooltip and reactive emoji.", examples: ["rating-tooltip"] },
    { id: "dual-range-input", title: "Dual range with input", description: "Range bounded by two inputs.", examples: ["dual-range-input"] },
    { id: "plus-minus", title: "Plus / minus buttons", description: "Stepper buttons alongside the slider.", examples: ["plus-minus"] },
    { id: "price-range", title: "Price range", description: "Formatted price range with an action button.", examples: ["price-range"] },
    { id: "vertical", title: "Vertical", description: "Vertical orientation.", examples: ["vertical"], align: "center" },
    { id: "vertical-input", title: "Vertical with input", description: "Vertical slider synced with an input.", examples: ["vertical-input"], align: "center" },
    { id: "vertical-dual-tooltip", title: "Vertical dual range and tooltip", description: "Vertical range with value tooltips.", examples: ["vertical-dual-tooltip"], align: "center" },
    { id: "object-position", title: "Object position", description: "Multiple labelled sliders with a reset-all action.", examples: ["object-position"] },
    { id: "price-histogram", title: "Price with histogram", description: "Range slider over a price-distribution histogram.", examples: ["price-histogram"] },
    { id: "equalizer", title: "Equalizer", description: "Five vertical bands with pill thumbs and tooltips.", examples: ["equalizer"], align: "center" },
  ],
  apiReference: [
    {
      component: "Slider",
      props: [
        { name: "modelValue", type: "number[]", default: "[0]", description: "Array of thumb values. Supports v-model." },
        { name: "min", type: "number", default: "0", description: "Min value." },
        { name: "max", type: "number", default: "100", description: "Max value." },
        { name: "step", type: "number", default: "1", description: "Increment between values." },
        { name: "disabled", type: "boolean", default: "false", description: "Disable input." },
        { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Layout direction of the track." },
        { name: "showTooltip", type: "boolean", default: "false", description: "Show a tooltip with the current value above each thumb." },
        { name: "tooltipContent", type: "(value: number) => string", default: "undefined", description: "Formatter for the tooltip label. Defaults to the raw value." },
      ],
      events: [
        { name: "update:modelValue", description: "Fires continuously as a thumb moves. Enables v-model." },
        { name: "value-commit", description: "Fires once when the user releases a thumb." },
      ],
    },
  ],
  accessibility: {
    keyboard: [
      { keys: ["←"], description: "Decreases the value by one step." },
      { keys: ["↓"], description: "Decreases the value by one step." },
      { keys: ["→"], description: "Increases the value by one step." },
      { keys: ["↑"], description: "Increases the value by one step." },
      { keys: ["Home"], description: "Sets the value to the minimum." },
      { keys: ["End"], description: "Sets the value to the maximum." },
      { keys: ["Page Up"], description: "Increases the value by a large step." },
      { keys: ["Page Down"], description: "Decreases the value by a large step." },
    ],
    notes: [
      "Each thumb has role=slider with aria-valuemin, aria-valuemax, and aria-valuenow.",
      "Provide an accessible label so screen readers announce the slider's purpose.",
    ],
  },
});
